### PR TITLE
[PUI 2.0] Proposed Project Scaffolding

### PR DESCRIPTION
**Pull request by mrtrimble**
Issue:
https://github.com/ritterim/platform-ui/issues/839

Updates:
- Proposed structure for the project
- Created a boilerplate TS file for JavaScript-enabled components
- Wired everything up to build via Vite
 - Configured Vite
   - Added `autoprefixer` plugin
   - Set main entry/output points
   - Building as a library, outputs CSS, ES Module, and universal JS
- Adds proposed CSS Reset
- Customization:
  - `platform-ui.config.js` file used to set design tokens
  - created `launch` command in `bin/build.js` to covert tokens to Sass Variables
  - Added `utilities/colors.scss` to demonstrate how to create CSS classes based off of config file  

Notes:
`src`
 - `components` - CSS and JS/TS for each component
 - `core` - reset, layouts, typography, and other default styles
 - `icons` - place to put icons
 - `themes` - place to put themes
 - `tokens` - place to put tokens
 - `utilities` - CSS utility classes

Diagram:
image

### CODE REVIEW

**Comment by mrtrimble** [comment]
Tagging:
@hougasian
@tedk13 

Please take a look at this proposed scaffolding for Platform UI, feel free to leave notes + comments here!

**Comment by tedk13** [comment]
I really like the idea of grouping the scss and js (if necessary) inside the same parent folder.

**Comment by hougasian** [comment]
**This is great groundwork! Thanks Ryan!**
Do we need to consider the approach of _workspaces_ documented [here](https://monorepo.guide/getting-started#setting-up-your-packages) (the link won't take you there, you have to scroll 😢)? It encompasses the needs of the repo and includes packages and the website (which I think could just be _website_ instead of _apps_). 

I believe we're still planning on breaking out utilities as a take-it-or-leave-it add on.

**Comment by mrtrimble** [comment]
@hougasian 

I haven't added any workspaces / monorepo settings into this yet as I still wasn't too sure if that was the route we were heading with it, we can definitely tackle that together next week!

Also, I just pushed up a proposed CSS Reset that is sort of a combination of two of the more modern CSS resets, see here:
https://github.com/ritterim/platform-ui/pull/855/files#diff-8f736b1523a7191889762ad3421ebbde74f00b892789bc028600596af839f591

**Pull request merged**
